#!/bin/bash -eu
# vim: set ft=sh

exec 3>&1 # make stdout available as fd 3 for the result
exec 1>&2 # redirect all output to stderr for logging

TMPDIR=${TMPDIR:-/tmp}

destination=$1

if [ -z "$destination" ]; then
  echo "usage: $0 <path/to/destination>" >&2
  exit 1
fi

payload=$(mktemp "$TMPDIR/promql-resource-request.XXXXXX")

cat > "$payload" <&0

endpoint=$(jq -r '.source.endpoint // ""' < "$payload")
query=$(jq -r '.source.query // ""' < "$payload")
last_ref=$(jq -r '.version.value // ""' < "$payload" )
timestamp=$(jq -r '.version.timestamp // ""' < "$payload" )
echo "$last_ref" > "${destination}/value"
echo "$timestamp" > "${destination}/timestamp"

jq -n "{
  \"version\": {\"value\": \"$last_ref\", \"timestamp\": \"$timestamp\"},
  \"metadata\": [
    {\"name\": \"endpoint\", \"value\": \"$endpoint\"},
    {\"name\": \"query\", \"value\": \"$query\"},
    {\"name\": \"value\", \"value\": \"$last_ref\"}
  ]
}" >&3