#!/bin/bash -eu
# vim: set ft=sh

exec 3>&1 # make stdout available as fd 3 for the result
exec 1>&2 # redirect all output to stderr for logging

echo >&2 "No put funtionality provided by promql-resource!"
exit 1